eureka:
    client:
        fetchRegistry: false
        registerWithEureka: false
        serviceUrl:
            defaultZone: http://localhost:8093/eureka
server:
    port: 8093
spring:
    application:
        name: discoveryservices
