eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8093/eureka
#    devtools:
#        restart:
#            enabled: true
#    instance:
#        instance-id: ${spring.application.name}:${spring.application.instance.instance_id:${random.value}}
server:
    port: 9087

spring:
    application:
        name: userservices
    datasource:
        password: Thewipper.
        url: jdbc:postgresql://localhost:5433/fidelity
        username: postgres
    jpa:
        hibernate:
            ddl-auto: update
