eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8093/eureka

server:
    port: 8091

spring:
    main:
        web-application-type: reactive

    application:
        name: api-gateway
    cloud:
        gateway:
            routes:
                - id: userservicess
                  uri: lb://USERSERVICES
                  predicates:
                      - Path=/person/**

                - id: accountservicess
                  uri: lb://ACCOUNTSERVICES
                  predicates:
                      - Path=/account/**


