eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka

server:
  port: 8086

spring:
  application:
    name: accountservices
  datasource:
    password: Thewipper.
    url: jdbc:postgresql://localhost:5433/fidelity
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update

