eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8093/eureka

server:
  port: 8087

spring:
  application:
    name: transactionservices
  datasource:
    password: Thewipper.
    url: jdbc:postgresql://localhost:5433/fidelity
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update


